<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>guide_dog_audio</name>
  <version>0.0.0</version>
  <description>Speaks text on the Go2's own speaker (espeak-ng + Go2 audio hub)</description>
  <maintainer email="janithchamikara13@gmail.com">janith</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>ament_index_cpp</depend>
  <depend>std_msgs</depend>
  <depend>guide_dog_interfaces</depend>
  <depend>unitree_api</depend>
  <depend>nlohmann-json-dev</depend>
  <depend>libssl-dev</depend>
  <depend>espeak-ng</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
